### ISSUE TITLE
Broken Icon in Elementary AppCenter

### ISSUE THREAD

**Issue by Andrewsudarikov** [lainsce/rakugaki#6] opened 2020-01-24 05:59 UTC
In the screenshot you can see the issue. Is it supposed to have an icon like that? 
![Screenshot from 2020-01-24 08 57 44](https://user-images.githubusercontent.com/18544958/73047712-b962fa00-3e87-11ea-845d-dd4a001ba11e.png)

**Comment by ryonakano** [comment] 2020-01-24 23:54
This is a duplicate of #4 and should be fixed in the next release of Rakugaki.

**Comment by lainsce** [comment] 2020-01-25 00:29
This is already fixed. Closing.

**Closed as completed by lainsce** 2020-01-25 00:29 UTC
